#!/bin/sh
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

terraform init -backend-config="conn_str=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/postgres?sslmode=${POSTGRES_SSL}"

TF_VAR_POSTGRES_HOST=${POSTGRES_HOST}
TF_VAR_POSTGRES_PORT=${POSTGRES_PORT}
TF_VAR_POSTGRES_SSL=${POSTGRES_SSL}
TF_VAR_POSTGRES_USER=${POSTGRES_USER}
TF_VAR_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

TF_VAR_KEYCLOAK_DB_NAME=${KEYCLOAK_DB_NAME}
TF_VAR_KEYCLOAK_DB_USER=${KEYCLOAK_DB_USER}
TF_VAR_KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

terraform apply -auto-approve -input=false -var-file="args.tfvars"
